added uv_check, basically uv_verify without building. added bandit in shell scripts

diff --git a/uv_verify b/uv_verify
--- a/uv_verify
+++ b/uv_verify
@@ -4,6 +4,7 @@
 
 PYTEST_FAIL_FLAG=0
 RUFF_LINT_FLAG=0
+BANDIT_FAIL_FLAG=0
 
 uv run ruff check
 if [ $? -ne 0 ]
@@ -18,9 +19,15 @@ then
     PYTEST_FAIL_FLAG=1
 fi
 
+uv run bandit togepy -r
+if [ $? -ne 0 ]
+then
+    BANDIT_FAIL_FLAG=1
+fi
+
 echo ""
-echo "----------------------------------------"
-echo "[1/3] Running ruff, linting..."
+echo "--------------- UV Verify: Conditional Building ---------------"
+echo "[1/4] Running ruff, linting..."
 if [ $RUFF_LINT_FLAG -eq 1 ]
 then
 	echo "✗ Lint failed"
@@ -28,8 +35,16 @@ else
 	echo "✓ Lint passed"
 fi
 echo ""
-echo "[2/3] Running tests..."
+echo "[2/4] Running tests..."
 if [ $PYTEST_FAIL_FLAG -eq 1 ]
+then
+	echo "✗ Tests failed"
+else
+	echo "✓ Tests passed"
+fi
+echo ""
+echo "[3/4] Running security checks..."
+if [ $BANDIT_FAIL_FLAG -eq 1 ]
 then
 	echo "✗ Tests failed"
 else
@@ -37,14 +52,14 @@ else
 fi
 
 echo ""
-echo "[3/3] Building package..."
-if [ $PYTEST_FAIL_FLAG -eq 1 ] || [ $RUFF_LINT_FLAG -eq 1 ]
+echo "[4/4] Building package..."
+if [ $PYTEST_FAIL_FLAG -eq 1 ] || [ $RUFF_LINT_FLAG -eq 1 ] || [ $BANDIT_FAIL_FLAG -eq 1 ]
 then
 	echo "✗ Building failed"
 	echo ""
 	echo ""
 	echo "--> Verify failed! Check above to see why"
-	echo "----------------------------------------"
+	echo "---------------------------------------------------------------"
 	exit 1
 else
 	echo "all conditions met, commencing build..."
